### ISSUE TITLE
Change TNS query string to a dictionary

### ISSUE THREAD

**Issue by emirkmo** [rhandberg/flows#15]
Change the TNS query string to dictionary with a base url string and a data dict. Also need to know whether the null/empty keys can be ignored and whether the dictionary can be submitted in any order by requests.

This is an enhancement on #11 and is a post-alpha step for #12. It's not needed to be done to get the basic system working.

**Comment by rhandberg** [comment]
The order definitely doesn't matter... The HTTP protocol doesn't care, and a Python dict doesn't have any "order" to begin with.

My guess is also that empty keys can be omitted, but you would have to test. Very simple - try to remove a key and see if the results change.

**Comment by emirkmo** [comment]
I will wait with this until December 27th, when they will change their base URL, as they may also change search keywords. At that point, I'll conver it into the correct format
